spring.application.name=back-Fpv

# Data base configuration
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=dbFpv

# Constantes
app.client.initial-balance=500000

# configuracion para envio de correos
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jllano@cidenet.com.co
spring.mail.password=nqth jcjt tgyx xabh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# AWS
cloud.aws.credentials.access-key=AKIA2AUOOVP6XB5JA3MH
cloud.aws.credentials.secret-key=ROU4RaqLrHEszlxB2Hu1TXxxxsOBagsJVvQfhaMv
cloud.aws.region.static=us-east-1



